# Generated by Django 5.2.12 on 2026-03-23 22:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название дисциплины')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
                ('course', models.PositiveSmallIntegerField(default=1, verbose_name='Курс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_groups', to=settings.AUTH_USER_MODEL, verbose_name='Куратор')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('record_book_number', models.CharField(max_length=50, unique=True, verbose_name='Номер зачетной книжки')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('enrollment_year', models.PositiveSmallIntegerField(verbose_name='Год поступления')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('academic_leave', 'Академический отпуск'), ('graduated', 'Выпустился'), ('expelled', 'Отчислен')], default='active', max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['last_name', 'first_name', 'middle_name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('grade_type', models.CharField(choices=[('quiz', 'Тест'), ('homework', 'Домашняя работа'), ('midterm', 'Рубежный контроль'), ('exam', 'Экзамен'), ('coursework', 'Курсовая')], default='quiz', max_length=30, verbose_name='Тип оценки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('graded_at', models.DateField(verbose_name='Дата выставления')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.subject', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['-graded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(verbose_name='Дата занятия')),
                ('status', models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал'), ('late', 'Опоздал'), ('excused', 'Уважительная причина')], default='present', max_length=20, verbose_name='Статус посещения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.subject', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
                'ordering': ['-lesson_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('student', 'subject', 'lesson_date'), name='unique_student_subject_lesson_date')],
            },
        ),
    ]
