# Generated by Django 5.2.12 on 2026-03-23 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, verbose_name='Балл риска')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=20, verbose_name='Уровень риска')),
                ('average_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Средний балл')),
                ('attendance_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Посещаемость, %')),
                ('missed_count', models.PositiveIntegerField(default=0, verbose_name='Количество пропусков')),
                ('debt_count', models.PositiveIntegerField(default=0, verbose_name='Количество долгов')),
                ('factors', models.JSONField(blank=True, default=list, verbose_name='Факторы риска')),
                ('recommendations', models.JSONField(blank=True, default=list, verbose_name='Рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_predictions', to=settings.AUTH_USER_MODEL, verbose_name='Кто рассчитал')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Прогноз',
                'verbose_name_plural': 'Прогнозы',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
